name: UltimateModeration
description: UltimateModeration
main: com.songoda.ultimatemoderation.UltimateModeration
version: Glaciar-1.0.0
author: [Songoda, bernardMC]
api-version: 1.19
softdepend: [spark, Vault, FabledSkyBlock]
commands:
  Court:
    description: View information on this plugin.
    default: false
    aliases: [punish, p]
    usage: /court
  History:
    description: View a player's criminal history
    default: false
    usage: /history <player>
  Alts:
    description: View a player potential alts
    default: false
    usage: /alts <player>
  ClearChat:
    description: Clear the chat
    default: false
    aliases: [cc]
    usage: /cc
  ToggleChat:
    description: Toggle chat
    default: false
    aliases: [tc]
    usage: /tc
  RandomPlayer:
    description: Random Player
    default: false
    aliases: [rp]
    usage: /rp
  Vanish:
    description: Vanish
    default: false
    aliases: [v]
    usage: /v
  Spy:
    description: Spy
    default: false
    usage: /spy
  Revive:
    description: Revive
    default: false
    usage: /revive
  InvSee:
    description: InvSee
    default: false
    usage: /invsee
  Freeze:
    description: Freeze
    default: false
    usage: /freeze
  ViewEnderChest:
    description: ViewEnderChest
    default: false
    usage: /ViewEnderChest
  Ban:
    description: Ban
    default: false
    usage: /ban
  Unban:
    description: Unban
    default: false
    usage: /unban
  Kick:
    description: Kick
    default: false
    usage: /kick
  KickWarning:
    description: KickWarn
    default: false
    usage: /kickwarning
  Mute:
    description: Mute
    default: false
    usage: /mute
  Unmute:
    description: Unmute
    default: false
    usage: /unmute
  Warn:
    description: Warn
    default: false
    usage: /warn
  RunTemplate:
    description: RunTemplate
    default: false
    usage: /runtemplate
  Ticket:
    description: Ticket
    default: false
    aliases: [tickets]
    usage: /ticket
  StaffChat:
    description: StaffChat
    default: false
    aliases: [sc]
    usage: /staffchat
  SlowMode:
    description: SlowMode
    default: false
    aliases: [sm]
    ussage: /slowmode